# Tavari - generate Cloudinary migration + rollback SQL
# Input:  backups/media-inventory-latest.csv  (fill the new_url column first)
# Output: sql/migrate-001-cloudinary.sql  (apply in Supabase SQL Editor)
#         sql/rollback-001-cloudinary.sql (paste to undo, generated from the backup)
# Read-only against Supabase; writes files only.

param(
  [string]$InventoryFile = "backups/media-inventory-latest.csv",
  [string]$BackupFile = "backups/media-backup-latest.json"
)

$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$invPath = Join-Path $root $InventoryFile
$bakPath = Join-Path $root $BackupFile
$sqlDir = Join-Path $root "sql"
if (-not (Test-Path -LiteralPath $sqlDir)) { New-Item -ItemType Directory -Path $sqlDir | Out-Null }

if (-not (Test-Path -LiteralPath $invPath)) { throw "Inventory not found: $invPath" }
if (-not (Test-Path -LiteralPath $bakPath)) { throw "Backup not found: $bakPath (run tools/export-media-backup.ps1 first)" }

$rows = @(Import-Csv -LiteralPath $invPath)
$errors = New-Object System.Collections.ArrayList

function Sql-Lit($s) { return "'" + ($s -replace "'", "''") + "'" }

# --- validate -------------------------------------------------------------
$resolved = 0
foreach ($r in $rows) {
  $new = ($r.new_url).Trim()
  if (-not $new) {
    if ($r.old_url -match '^https://res\.cloudinary\.com/') { $r.new_url = $r.old_url; $resolved++; continue }
    [void]$errors.Add("MISSING new_url for $($r.scope) [$($r.trip_id)] #$($r.index): $($r.old_url)")
    continue
  }
  if (-not ($new -match '^https://res\.cloudinary\.com/[^/]+/image/upload/.+')) {
    [void]$errors.Add("NOT A CLOUDINARY UPLOAD URL for $($r.scope) [$($r.trip_id)] #$($r.index): $new")
    continue
  }
  if ($new -match '\s') { [void]$errors.Add("WHITESPACE in new_url for $($r.scope) #$($r.index)"); continue }
  $r.new_url = $new
  $resolved++
}
$complete = ($resolved -eq $rows.Count)
if (-not $complete) {
  $pendingPath = Join-Path $sqlDir "pending-rows.txt"
  Set-Content -LiteralPath $pendingPath -Value $errors -Encoding UTF8
  Write-Host "$($rows.Count - $resolved) of $($rows.Count) rows still need a Cloudinary URL (details: $pendingPath)" -ForegroundColor Yellow
  Write-Host "Rollback SQL will still be (re)generated; migration SQL will be skipped." -ForegroundColor Yellow
}
$dupes = $rows | Where-Object { $_.new_url } | Group-Object new_url | Where-Object { $_.Count -gt 1 }
if ($dupes) { Write-Warning ("Duplicate new_url values detected: " + (($dupes | ForEach-Object { $_.Name }) -join ", ")) }

# --- migrate --------------------------------------------------------------
if ($complete) {
$migrate = New-Object System.Collections.ArrayList
[void]$migrate.Add("-- Tavari - Cloudinary migration (generated $(Get-Date -Format 'yyyy-MM-dd HH:mm'))")
[void]$migrate.Add("-- Generated by tools/gen-migration-sql.ps1 from $InventoryFile")
[void]$migrate.Add("-- Review, then run in Supabase -> SQL Editor. No schema or RLS changes.")
[void]$migrate.Add("begin;")
[void]$migrate.Add("")

$tripsGroups = $rows | Where-Object { $_.scope -like "trips.*" } | Group-Object trip_id, field | Sort-Object { [int]$_.Values[0] }, { $_.Values[1] }
foreach ($g in $tripsGroups) {
  $tripId = $g.Values[0]; $field = $g.Values[1]
  $ordered = $g.Group | Sort-Object { [int]$_.index }
  $vals = ($ordered | ForEach-Object { Sql-Lit $_.new_url }) -join ", "
  $title = $ordered[0].trip_title
  [void]$migrate.Add("-- trips.$field - $title (id=$tripId)")
  [void]$migrate.Add("update public.trips set $field = array[$vals] where id = $(Sql-Lit $tripId);")
}

$galleryRows = $rows | Where-Object { $_.scope -eq "gallery.media_url" } | Sort-Object { [int]$_.index }
if ($galleryRows) {
  [void]$migrate.Add("")
  foreach ($r in $galleryRows) {
    [void]$migrate.Add("-- gallery position $($r.index)")
    [void]$migrate.Add("update public.gallery set media_url = $(Sql-Lit $r.new_url) where id = $(Sql-Lit $r.trip_id);")
  }
}
[void]$migrate.Add("")
[void]$migrate.Add("commit;")
[void]$migrate.Add("")
[void]$migrate.Add("-- Verify (expect 0 rows):")
[void]$migrate.Add("-- select id, title from public.trips where image_urls && array(select unnest(image_urls) from public.trips) is false;")
[void]$migrate.Add("-- select count(*) as still_on_supabase from (")
[void]$migrate.Add("--   select unnest(image_urls) u from public.trips")
[void]$migrate.Add("--   union all select unnest(accommodation_photos) from public.trips")
[void]$migrate.Add("--   union all select media_url from public.gallery where media_url is not null")
[void]$migrate.Add("-- ) x where u like '%supabase.co/storage%';")

$migratePath = Join-Path $sqlDir "migrate-001-cloudinary.sql"
Set-Content -LiteralPath $migratePath -Value ($migrate -join "`n") -Encoding UTF8
"Migration SQL: $migratePath ($($rows.Count) urls)"
}

# --- rollback (from backup) ------------------------------------------------
$backup = Get-Content -LiteralPath $bakPath -Raw | ConvertFrom-Json

$rollback = New-Object System.Collections.ArrayList
[void]$rollback.Add("-- Tavari - ROLLBACK to Supabase Storage URLs (generated $(Get-Date -Format 'yyyy-MM-dd HH:mm'))")
[void]$rollback.Add("-- Source backup: $BackupFile (exported $($backup.exported_at))")
[void]$rollback.Add("-- Paste this in Supabase -> SQL Editor to undo migrate-001-cloudinary.sql.")
[void]$rollback.Add("begin;")
[void]$rollback.Add("")
foreach ($t in $backup.trips) {
  $imgs = @($t.image_urls); $accs = @($t.accommodation_photos)
  if ($imgs.Count) {
    [void]$rollback.Add("-- trips.image_urls - $($t.title)")
    [void]$rollback.Add("update public.trips set image_urls = array[$(($imgs | ForEach-Object { Sql-Lit $_ }) -join ', ')] where id = $(Sql-Lit $t.id);")
  }
  if ($accs.Count) {
    [void]$rollback.Add("-- trips.accommodation_photos - $($t.title)")
    [void]$rollback.Add("update public.trips set accommodation_photos = array[$(($accs | ForEach-Object { Sql-Lit $_ }) -join ', ')] where id = $(Sql-Lit $t.id);")
  } else {
    [void]$rollback.Add("-- trips.accommodation_photos - $($t.title) (was empty)")
    [void]$rollback.Add("update public.trips set accommodation_photos = '{}'::text[] where id = $(Sql-Lit $t.id);")
  }
}
[void]$rollback.Add("")
foreach ($g in $backup.gallery) {
  if (-not $g.media_url) { continue }
  [void]$rollback.Add("-- gallery position $($g.position)")
  [void]$rollback.Add("update public.gallery set media_url = $(Sql-Lit $g.media_url) where id = $(Sql-Lit $g.id);")
}
[void]$rollback.Add("")
[void]$rollback.Add("commit;")

$rollbackPath = Join-Path $sqlDir "rollback-001-cloudinary.sql"
Set-Content -LiteralPath $rollbackPath -Value ($rollback -join "`n") -Encoding UTF8

"Rollback SQL:  $rollbackPath"


